### ISSUE TITLE
WEB网页直接播放报错404，所有客户端都正常播放

### ISSUE THREAD

**Issue by sleikang** [Akimio521/MediaWarp#8]
![image](https://github.com/user-attachments/assets/537ef0ca-8a11-4329-a175-ee444ecd51f7)
![image](https://github.com/user-attachments/assets/e02ef2c8-e626-4163-b430-7b54378565ef)
试了EMBY官方客户端 yamby afusekt都可以正常播放 但是网页直接播放就报错404，如果不走[MediaWarp]网页直接播放是正常的，直接播放会走strm里面的直连

**Comment by Akimio521** [comment]
v0.0.3有同样的问题吗

**Comment by sleikang** [comment]
> v0.0.3有同样的问题吗

没有用过0.0.3用的是最新的版本 测试web播放就会404 不清楚是不是代理协议的问题，所以目前的解决办法只能是根据UA屏蔽web跳转302，然后所有终端播放都正常了

**Comment by Akimio521** [comment]
建议把v0.0.1到0.0.3的版本都测试一遍，之前我确认过web是可以正常302的

**Comment by Akimio521** [comment]
> > v0.0.3有同样的问题吗
> 
> 
> 
> 没有用过0.0.3用的是最新的版本 测试web播放就会404 不清楚是不是代理协议的问题，所以目前的解决办法只能是根据UA屏蔽web跳转302，然后所有终端播放都正常了 

如果是httpStrm这么做也还行，但是并不适合AlistStrm

**Comment by sleikang** [comment]
> > > v0.0.3有同样的问题吗
> > 
> > 
> > 
> > 没有用过0.0.3用的是最新的版本 测试web播放就会404 不清楚是不是代理协议的问题，所以目前的解决办法只能是根据UA屏蔽web跳转302，然后所有终端播放都正常了 
> 
> 如果是httpStrm这么做也还行，但是并不适合AlistStrm

我看了 aliststrm 部分的代码基本逻辑差不多，只是 alist 部分从 alist 接口获取播放链接，估计在 web网页播放也会 404，而且我 httpstrm里面的内容就是你的另外一个项目生成的 alist 的 strm 文件，我看这个项目里面 aliststrm 部分其实就是再从 alist 接口获取文件直连，和 httpstrm部分本质应该没区别，但是获取路径应该方式应该有点问题我这边是没法获取到直连因为挂载的目录和 alist 的根目录层级有区别

**Comment by Akimio521** [comment]
> 我看了 aliststrm 部分的代码基本逻辑差不多，只是 alist 部分从 alist 接口获取播放链接，估计在 web网页播放也会 404，而且我 httpstrm里面的内容就是你的另外一个项目生成的 alist 的 strm 文件，我看这个项目里面 aliststrm 部分其实就是再从 alist 接口获取文件直连，和 httpstrm部分本质应该没区别，但是获取路径应该方式应该有点问题我这边是没法获取到直连因为挂载的目录和 alist 的根目录层级有区别

我的意思是如果直接让上游媒体服务器处理AlistStrm是肯定会播放失败的，所以这么修改其实并不合理。

之前版本我测试过web播放是正常的，但是完成后后续我就没有复测了，所以建议找到是哪个版本开始无法正常播放。而且播放失败不仅有VideoHandler下面会造成影响，可能是其他的api接口变化使得客户端发送的请求有变化

**Comment by sleikang** [comment]
> > 我看了 aliststrm 部分的代码基本逻辑差不多，只是 alist 部分从 alist 接口获取播放链接，估计在 web网页播放也会 404，而且我 httpstrm里面的内容就是你的另外一个项目生成的 alist 的 strm 文件，我看这个项目里面 aliststrm 部分其实就是再从 alist 接口获取文件直连，和 httpstrm部分本质应该没区别，但是获取路径应该方式应该有点问题我这边是没法获取到直连因为挂载的目录和 alist 的根目录层级有区别
> 
> 我的意思是如果直接让上游媒体服务器处理AlistStrm是肯定会播放失败的，所以这么修改其实并不合理。
> 
> 之前版本我测试过web播放是正常的，但是完成后后续我就没有复测了，所以建议找到是哪个版本开始无法正常播放。而且播放失败不仅有VideoHandler下面会造成影响，可能是其他的api接口变化使得客户端发送的请求有变化

试了0.0.2版本直接启动不起来 0.0.3不报错404了但是报错当前没有兼容的流。请稍后再试或联系您的管理员以获取详细信息。但是不经过302是什么视频都可以播放的，只能说如果这种一刀切的方式不合适的话可以加个config 让用户自己选择是否web走302，不过我感觉web走302意义不大，因为本身浏览器解码性能基本都有问题的最终还是得靠服务器解码，也可以参考下[emby2Alist](https://github.com/bpking1/embyExternalUrl/tree/main/emby2Alist)这个项目好像是遇到302播放失败会自动跳转服务器解码播放

**Comment by sleikang** [comment]
应该0.0.5的框架有点问题，我web播放虽然我自己拦截了302跳转 刚才115网盘风控了 alist请求失效，web在播放失败的时候也出现了302，而且0.0.5会一次播放会出现多次触发302那个接口

**Comment by sleikang** [comment]
今天又试了0.0.3还是出现没有兼容的视频流。估计还是网页直接播放不支持302的方式
